# Generated by Django 5.1 on 2024-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='slides/')),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(default='#')),
            ],
        ),
    ]
