# Generated by Django 5.1 on 2024-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='button_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
