# Generated by Django 5.1 on 2024-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slide_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='slides/'),
        ),
    ]
