# Generated by Django 5.1 on 2024-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_slide_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='background_image',
            field=models.ImageField(default=1, upload_to='slides/'),
            preserve_default=False,
        ),
    ]
